---
title: "Development of Math 201"
format: 
  html:
    toc: true
editor: visual
---

The new development of M201 is to address two goals: (1) The UN [Sustainable Development Goals](https://www.globalgoals.org/goals/) (SDG) and (2) Bryant 2030's vision skill and learning goals, which can be found [here](gen_ed.pdf).

```{=html}
<!--

We ask that you incorporate at least a project or a case study fulfilling the [Sustainable Development Goals](https://www.globalgoals.org/goals/) (SDG) requirement
to your M201's syllabus. We also ask that the projects/case studies should count for at least 10% of the total grades. The data used for the project/case study might be existing available datasets or might be collected by the students using surveys. The project/case study could be a semester long project or shorter.

Another aspect of the development is the computational software used for the course. To this end, we are encouraged to use Excel for the class. Thus, we ask that you use Excel as much as possible, if not 100%, for the statistical computations required software.

-->
```
For the Fall 2023 semester, we would like to set realistic minimums for the content change. After each semester, we would like to re-evaluate the new course material and consider stronger minimum requirements for SDG. Also, having at least one semester of each course under our belt, we can more confidently assess the possibility of having a common project across all classes.

Specifically, in the Fall 2023, we would like you to

-   Incorporate at least one of the below six SDG in a case study/project. The incorporated case study/project should count for at least 10% of the total grade.

    -   [SDG 3](https://www.globalgoals.org/goals/3-good-health-and-well-being/): Good Health & wellbeing
    -   [SDG 4](https://www.globalgoals.org/goals/4-quality-education/): Quality Education\
    -   [SDG 8](https://www.globalgoals.org/goals/8-decent-work-and-economic-growth/): Decent Work and Economic Growth
    -   [SDG 7](https://www.globalgoals.org/goals/7-affordable-and-clean-energy/): Affordable and Clean Energy\
    -   [SDG 9](https://www.globalgoals.org/goals/9-industry-innovation-and-infrastructure/): Industry, Innovation, and Infrastructure\
    -   [SDG 11](https://www.globalgoals.org/goals/11-sustainable-cities-and-communities/): Sustainable Cities and Communities

-   At a minimum, introduce statistics using Excel (Data Analysis functions). Excel needs not be used exclusively.

-   Make an effort to include regression analysis

The bullets listed above are a change from the old M201's requirements. The main course content change is a shift toward more applied statistics in line with the SDG's, and the use of Excel. The theory change is minor in terms of topics, mainly to incorporate regression and our syllabus examples (below in section 1 and 2) show a couple of ways to achieve this by dropping some relatively minor topics (chi-squared testing, combination/permutations,...).

## 1. Project/Case Study Examples

To help you develop your own project, we list here a few examples. If you have a research project to share, please let us know so that we can include it here. Please notice that project 2 (Four-Phase Project) is a semester long project.

|     | Project                                                      | Data                                              | SDG                     | Author                                                                        |
|-------------|---------------|-------------|-------------|--------------------|
| 1   | [World Happiness](happiness_M201_handout.pdf)                | [Data](world-happiness-report-2021_main_vars.xls) | Good Health & wellbeing | [William Zywiak](https://www.bryant.edu/academics/faculty/zywiak-william)     |
| 2   | [Four-Phase Project](PROJECT%20with%204%20phases%20sp23.pdf) | Collected by Students                             |                         | [Nancy Beausoleil](https://www.bryant.edu/academics/faculty/beausoleil-nancy) |

: {.striped}

## 2. Syllabus Examples

-   Syllabus 1: [Word](2023_Syllabus%20201.DOC), [pdf](MATH201_D_Excel_syllabus_Fall_2023.pdf) by William Zywiak. This syllabus incorporates the World Happiness project listed in the previous section.

-   Syllabus 2: [Word](MATH201_D_Excel_syllabus_Fall_2023.docx), [pdf](2023_Syllabus%20201_JB.pdf) by Jim Bishop

## 3. Excel Tutorial

One way to do statistics in Excel is to use the [Analysis ToolPak](https://support.microsoft.com/en-gb/office/use-the-analysis-toolpak-to-perform-complex-data-analysis-6c67ccf0-f4a9-487c-8dec-bdb5a2cefab6). We list a few tutorial videos here for your references.

-   [Installation](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=38955015-791d-4394-8f0c-b0500094adf2).

-   [Descriptive statistics](https://youtu.be/3F_V5alJubk).

-   [Hypothesis Testing & Estimation](https://www.youtube.com/playlist?list=PLD3fYc0bAjC-l2bN1Ekuhte7BO-LXKi9c)

-   Regression: [1](https://youtu.be/L_a8Z0BVjyM), [2](https://youtu.be/0lpfmFnlDHI), [3](https://youtu.be/9wX1a1J4WOI)

## 4. Data

We list below data that could be used for a project.

|     | Data                                                                                                            | Download                                              | SDG                        |
|-------------|---------------------------------|--------------|-------------|
| 1   | World Happiness                                                                                                 | [Download](world-happiness-report-2021_main_vars.xls) | Good Health and Well-Being |
| 2   | [Gender Pay Gap - Europe](https://www.kaggle.com/datasets/gianinamariapetrascu/gender-pay-gap-europe-2010-2021) | [Download](data/pay_gap_Europe.xlsx)                  | Gender Equality            |
| 3   |                                                                                                                 |                                                       |                            |

: {.striped .hover}

## 5. What is a statistical project?

According to the [American Statistical Association](https://www.amstat.org/asa/files/pdfs/EDU-statproject.pdf):

> A statistical project is the process of answering a research question using statistical techniques and presenting the work in a written report.

For more on using projects in introductory statistics courses:

[Discovery Learning Projects in Introductory Statistics](http://faculty.ung.edu/DJSpence/NSF/materials.html)

## 6. Q&A

1.  Is it required to use Excel for the statistical analysis in the course?

    -   *We are encouraged to use more Excel on the Gen-ed Math classes. Using Excel in both M110 and M201 will help the student consistently learn and strengthen their Excel skills.* For the fall 2023, Excel needs not be used exclusively.
